version: '3'

services:
  app:
    build: ./
    ports:
      - 80:80
    networks:
      - mynetwork
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/storage:/prometheus
    ports:
      - 9090:9090
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana-enterprise:8.2.0
    ports:
      - 3000:3000
    volumes:
      - ./grafana/storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json:ro
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
